apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run:  "5in1"
  name: "5in1"
spec:
  containers:
  - image: machlovi/5in1:latest
    name: "p1"
    imagePullPolicy: IfNotPresent
    #  Using CMD to acces run the python file and change 
    #  the @threading to a value to a value that will be pass while runing bash file
    command: ["/bin/bash", "-c"]
    args: ["python3 /5in1.py"]
  restartPolicy: Never
